### ISSUE TITLE
MBIN File Request (TkSceneNodeData)

### ISSUE THREAD

**Issue by Crackfoxxxy** [emoose/MBINCompiler#11]
Hi,

Is it possible you could get the Compiler to be able to read this file?

POLICESHIP.SCENE.MBIN

in 

\MODELS\COMMON\SPACECRAFT\POLICE

Thanks,

Crackfoxxxy

**Comment by Crackfoxxxy** [comment]
Oh and great work by the way :D

**Comment by emoose** [comment]
Hmm, this uses the TkSceneNodeData template which is pretty big, might take a while to map this out but I'll leave this open so it's a priority.

**Comment by naomichan** [comment]
#25
