### ISSUE TITLE
List of working templates?

### ISSUE THREAD

**Issue by ViggyNash** [emoose/MBINCompiler#12]
Is it possible to have a list of the currently supported templates or files, so we know which ones are currently accessible using this tool? I have tried this tool on several different mbin files and I always get the "Failed to deserialize template" error.

**Comment by emoose** [comment]
There's a list of the supported files/templates in the UnitTests project [here](https://github.com/emoose/MBINCompiler/blob/master/MBINCompilerTests/UnitTests.cs), I'll try and keep this up to date whenever more templates are added.
