### ISSUE TITLE
Request: Can we get a compiled EXE file?

### ISSUE THREAD

**Issue by Galenmacil** [emoose/MBINCompiler#14]
For those like me who lack the knowledge required to compile it...

**Comment by kunal3** [comment]
It is compiled! All you need to do is navigate to this folder-
(Location of unzipped folder)\MBINCompiler-master\MBINCompiler\bin\Debug\
Inside a command prompt window, and type "./MBINCompiler [InputPath]"

**Comment by Galenmacil** [comment]
Oh! Thanks. Trying it out...

**Comment by Raided** [comment]
He is right, there is no compiled .exe in source. Here is one I prepared earlier!
http://www.mediafire.com/download/6zor9ex2xefpc3z/MBINCompiler.exe

Just drag the .MBIN onto the .exe

**Comment by emoose** [comment]
I'll try and setup AppVeyor later to auto-compile builds with each commit, main reason I haven't provided builds is that MBINCompiler is still being worked on and changes are pretty frequent, so making a release for every commit would take up some time, AppVeyor should help with that though.

**Comment by kunal3** [comment]
Isn't compiling as easy as hitting Run in Visual Studio? That's all I did and it took less than 3 seconds to compile. That's why I have the exe in debug folder, I remember now. @emoose

**Comment by emoose** [comment]
It's easy to compile but setting up github releases etc would take time, I'd rather only do that for major releases instead of every small change. This won't be a problem soon though once AppVeyor is setup as that can take care of building each change for us.

**Comment by Galenmacil** [comment]
Much appreciated!
