### ISSUE TITLE
How are other people recompiling?

### ISSUE THREAD

**Issue by SamStenner** [emoose/MBINCompiler#17]
Hi Emoose,

On the No Man's Sky Mods website, people are uploading mods, so I've looked at them in .exml formats, to see the differences. They're pretty cool, but how come they're turning them back in to MBIN files without a tool? If you're planning on making one, why not just use whatever they're using?

Thanks :)
Sam

**Comment by emoose** [comment]
AFAIK they're using a hex editor to edit it manually, right now you can use MBINCompiler to find the value of what you want to edit, then search using a hex editor for that value, hacky way of doing it but it seems to work.

**Comment by SamStenner** [comment]
Ah okay, I see. Seems very hacky to me, but I guess it works! Great stuff though, thanks.
