### ISSUE TITLE
2 Requests

### ISSUE THREAD

**Issue by SamStenner** [emoose/MBINCompiler#2]
Hi,

First of all, great job on the tool, works great for me so far. 

1. When will I be able to turn my .exml files back into .mbin files? I'm currently looking to fix the stretched player HUD when using 3 monitors (5760x1080). I saw your post about the PLAYERHUD.MBIN file, and I decompiled it and went through it. I think I've found something, but can't test it yet because I can't recombine the exml files into mbin files.

2. How can I add my own templates? The supported ones extract fine, but there are some interestingly named files I'd like to dig into, but can't because they're not yet supported. Can I do this myself? If so, how?

Many thanks, keep up the good work!
Sam.

**Comment by emoose** [comment]
EXML -> MBIN will be added very soon, probably going to look into it tomorrow.

The link Guide13007 gave is a decent guide on how to find the templates, but it's probably not really worth looking into if you haven't done any reverse engineering before.

Templates aren't really that much of an issue though, the games MBIN files only use about ~115 unique ones, much fewer than I thought initially. Once recompiling is done it shouldn't be long until we've got them all mapped.

**Comment by Guard13007** [comment]
Awesome, glad to know it's coming along well.

@emoose Any recommended materials for someone new to reverse engineering to learn about it?

**Comment by kunal3** [comment]
Second Guard13007 about material on RE, would like to learn as well. I know C#, can you please comment your code? I could probably go from there.
