### ISSUE TITLE
UI/HUD Layer data implement request (GcNGuiLayerData)

### ISSUE THREAD

**Issue by NoMansMods** [emoose/MBINCompiler#28]
I have tried messing around with these types of files myself, but to no avail. Since I have no idea what I'm doing, please take a look at these types of files as it would help greatly! :) 

Examples of files that use this format are located in"GAMEDATA\UI\COMPONENTS". 

Please and thank you!

**Comment by Shadwar** [comment]
Pulled.

**Comment by emoose** [comment]
Yep, added in #30, thanks @Shadwar.
