### ISSUE TITLE
Change padding fields to use [NMS(Ignore = true)] attribute

### ISSUE THREAD

**Issue by emoose** [emoose/MBINCompiler#31]
~~Right now we align certain templates which don't follow standard alignment with "PaddingXXX" fields, when it comes to serializing to XML we check if the field name starts with "Padding", and if so we don't include it in the XML.~~

~~However some of the games templates actually include fields with names that start with "Padding", atm to get these to show in the XML you have to spell it differently otherwise it won't be displayed. (see #30)~~

~~We should probably change these padding fields to start with "_Padding" instead, since it's unlikely the game would have any fields starting with that name.~~

EDIT: Above shouldn't be an issue now that we have an attribute for ignoring fields, just have to go through and make sure all the padding fields are using it.

**Comment by Atvaark** [comment]
Alternatively you could add a custom **[EXmlIgnore]**-attribute to each field that should be ignored.

**Comment by naomichan** [comment]
I call them "EmptyNode"
