### ISSUE TITLE
Licensing (GPL3?)

### ISSUE THREAD

**Issue by emoose** [emoose/MBINCompiler#32]
Should have included this from the start really, but better late than never.

I'm all for going GPL v3, but if anyone is against it or you have a different choice in mind let me know here. I'll leave this issue up for the next 24 hours to let everyone see it.

**Comment by Bananasft** [comment]
If it's unclear to anyone, the full license and a small explanation can be found here http://choosealicense.com/licenses/gpl-3.0/

**Comment by Guard13007** [comment]
I'd prefer a license which doesn't restrict the user as much, like the LGPL or MIT license.

**Comment by emoose** [comment]
LGPL sounds fine to me, I don't mind people using MBINC as part of a closed source app as long as the MBINC portion is open-sourced, which it seems the GPL wouldn't allow but LGPL would. Anyone have any objections to LGPL?

**Comment by emoose** [comment]
Added in 92816726fb24ca4c6742fc15339b00f5a0a372e7
