### ISSUE TITLE
Change MarshalAs(SizeConst) to NMS(Size), change xx1,xx2,xx3 fields to arrays...

### ISSUE THREAD

**Issue by emoose** [emoose/MBINCompiler#44]
I'll go through and do some of these later, but if anyone wants to help out feel free.

**Comment by Atvaark** [comment]
The C# compiler provides some syntactic-sugar for attribute classes that end with the *Attribute*-suffix by the way.

You can simply omit the suffix when using the attribute.

e. g.
`
[NMS(Ignore = true)]
`

**Comment by naomichan** [comment]
NMSString should be kept for LIsts, it doesn't support primitive types yet either, and I'm too scared to touch the code as refactoring some stuff for #48 broke a few unexpected things.
