### ISSUE TITLE
MBIN serializer broken?

### ISSUE THREAD

**Issue by emoose** [emoose/MBINCompiler#53]
Noticed that I commented out part of the recompileFiles test which compares the decompiled exml of the recompiled mbin with the exml of the original, just uncommented it and it fails straight away on the first file, METADATA\SIMULATION\SPACE\AISPACESHIPMANAGER.MBIN

The structure is all there, but the values of the strings are blank. The remade MBIN is also only 0x60 bytes, so there's definitely something wrong here.

Making this to remind myself to look into this tomorrow, if anyone wants to try helping in the meantime be my guest.

**Comment by Bananasft** [comment]
[GcAISpaceshipInstanceData.cs](https://github.com/emoose/MBINCompiler/blob/master/MBINCompiler/Models/Structs/GcAISpaceshipInstanceData.cs) contains a `string` using the `NMSAttribute`, which is currently ignored while deserializing exml.

I fixed this in #50.

**Comment by emoose** [comment]
It shouldn't be getting ignored, I already pushed a fix for that a few commits ago: https://github.com/emoose/MBINCompiler/commit/bdb37d98ae3c16a6162275b9ae43f69cc93c493c#diff-53c1d1d10f57a89a0704071f7b08e3e7R72

**Comment by emoose** [comment]
Looks like that fixed it @Bananasft, nice work.

There's still some issues with templates that use GcAudioWwiseEvents though, some reason the value inside GcAudioWwiseEvents is being set to 0 after being recompiled, might be an issue with the xml deserializer.

**Comment by emoose** [comment]
Ah the DeserializeEXml method didn't support unsigned fields, easy fix: 0977e1c92dda7aad12aa0315ad9a94a52cce1c73

That about does it, tests seem to run fine for me now :100:
