### ISSUE TITLE
cGcUIGlobals

### ISSUE THREAD

**Issue by lobolmart** [emoose/MBINCompiler#54]
hello,

seems that the template in question doesn't follow the standard scheme of using the add<Type> subroutines.

NMS GOG v1.0
imagebase: 140000000
section 1 @ 00001000

some observations:
00000001401024D0 is the MBIN loader for said template.
using the sceFios API it reads 96 bytes of header (i assume) and then places the rest in a static pointer to a buffer (for me that's at 00000001416270D0 @ .data).

that buffer is accessed in multiple locations including:
0000000140164930
which pretty much can be used to define the raw struct / model. but there are no literals to define the property names - e.g. unlike this one:

```
.text:00000001401063F5                 lea     rdx, aTimestamp ; "Timestamp"
.text:00000001401063FC                 mov     [rsp+58h+var_30], 7FFFFFFFh
.text:0000000140106404                 mov     [rsp+58h+var_38], 80000000h
.text:000000014010640C                 call    xml_addIntProperty
```
aTimestamp @ .rdata

so my point is (unless i'm missing something) that this template might be a big difficult to define in XML without testing each individual field?

BTW, this mod:
http://nomansskymods.com/mods/fast-actions/
does modify certain 5-6 bytes of the same template's MBIN, so the author must have figured out what to modify, probably via trial and error.

ideas are welcome.

**Comment by emoose** [comment]
It seems that all the globals files are loaded like this, and missing the xml_startTemplate functions for them etc, not really sure why but it's going to be a pain for us.

As you said each field would need to be tested to work out what it does. Some people like the one you linked have managed to figure out individual fields, but afaik nobody has mapped any whole files yet (beside the debug options, which we sorta got lucky with), would probably be a lot easier if these people would contribute their findings but that hasn't happened yet :(

Maybe we should make skeleton templates for them based on the raw struct stuff (like the 140164930 one you gave), those at least sorta give us the types and offsets of the fields, then people could just rename them then once they've figured out what they're for.

**Comment by lobolmart** [comment]
> Maybe we should make skeleton templates for them based on the raw struct stuff (like the 140164930 one you gave), those at least sorta give us the types and offsets of the fields, then people could just rename them then once they've figured out what they're for.

i agree, seems like the correct thing to do for now.

**Comment by naomichan** [comment]
I tried making a raw struct of GcUIGlobals, but I got too confused after the 24th parameter. It has just over 1,000 parameters, mapping it out manually is going to be a while.

I'm going to try looking into it tomorrow if I have time.

**Comment by SirBarclay** [comment]
I know SpaceShipGlobals uses a few templates that can be found in full form in IDA, the SpaceshipTravelData (I think its whats it called), is used in it.  So I think starting backwards with them would be the best approach.

I know SpAnser has somewhat found his way around atleast a few of the MBINs without the help of mbincompiler and just using an IDA / Hex Editor, I think he might be able to help with reversing them.

Mapping out all templates, not just ones listed in #13 would be the start and might help with putting the jigsaw together, I think.

**Comment by lobolmart** [comment]
@naomichan 
> I tried making a raw struct of GcUIGlobals, but I got too confused after the 24th parameter. It has just over 1,000 parameters, mapping it out manually is going to be a while.

> I'm going to try looking into it tomorrow if I have time.

monday i can write a c# parser to automate over the mnemonics or disassembled output for 0000000140164930 and generate the raw struct. possibly the same parser can be made reusable for the rest of the direct access templates (buffers).

AFK until then, so you can decide if you'd like to focus on something else in the meantime or give this another try.

**Comment by naomichan** [comment]
@lobolmart some of the DWORDs are actually _Float32s_

Might have to do some validation to see what is a float and what is an int.

**Comment by emoose** [comment]
I've mapped out the skeleton of three globals already - GcPlacementGlobals, GcSmokeTestOptions and GcTerrainGlobals - they seem right but of course we can't be sure :smile: : 

I'm thinking these skeletons probably shouldn't be in the same folder as the other structs though, maybe we should put them in /Models/Structs/Globals/ instead, or maybe /Models/Structs/Skeletons/ ?

**Comment by lobolmart** [comment]
@naomichan 
> some of the DWORDs are actually Float32s
> Might have to do some validation to see what is a float and what is an int.

yep, i've noticed on friday. will try to validate the default values.

@emoose 
> Also maybe we should add an attribute for unfinished templates, so that users can get a warning that the template's structure is unfinished and could change at any time. That way users can't complain when they try compiling an unfinished template from 3 months ago against a MBINC that has the completed template using different field names, etc.

> The warning could be just a simple Console.WriteLine telling them, but if possible we should probably include it as an XML comment too, since most users probably wouldn't see the console output.

sounds good. BTW, if they decide to change templates, there has to be a way to pick the right struct. the user can provide a CMD flag in the lines of -NMSVersion=103 (i.e. "i'm targeting 1.03") and perhaps a struct from a particular namespace has to be used if the related template changed within a patch.

**Comment by naomichan** [comment]
we can probably change NMSAttribute to be able to declare fields or classes to behave differently only after a certain MBIN date.

**Comment by lobolmart** [comment]
@emoose, @naomichan 

some progress so far.

in:
https://gist.github.com/lobolmart/d959a96166b033d153f42faae19b103c
out:
https://gist.github.com/lobolmart/5bb618857a587fbc5c799d9bf5d40fa9

i may be lacking some understanding about arrays and padding in NMSTemplate and also i may have messed up somewhere, so feel free to correct me.

there is a subroutine in there called `sub_140162E50` which acts on a portion of the buffer.
said portion is treated as a byte[], for now.

**Comment by emoose** [comment]
Whoa, good stuff @lobolmart!

>there is a subroutine in there called sub_140162E50 which acts on a portion of the buffer.
said portion is treated as a byte[], for now.

That's probably a child template, from what I've seen child templates usually have the xml template stuff (giving us the field names/types/etc) still in the exe, I wrote a little about finding it here: https://github.com/emoose/MBINCompiler/issues/62#issuecomment-243283093

Also the globals are usually loaded into a pre-allocated buffer in memory, you can navigate to this buffer in IDA and find xrefs to each field, might be useful for your script since those xrefs can usually give us the type of the field if we aren't sure.

**Comment by lobolmart** [comment]
> That's probably a child template, from what I've seen child templates usually still have the xml template stuff (giving us the field names/types/etc) in the exe, I wrote a little about finding it here: #62 (comment)

yes, it could be. will attempt to find more info about it tomorrow.

> Also the globals all seem to be loaded into a pre-allocated buffer in memory, you can navigate to this buffer in IDA and find xrefs to each field, might be useful for your script since those xrefs can usually give us the type of the field if we aren't sure.

i see some oddities:
```
  *(_QWORD *)(a1 + 260) = 1056964608i64;
  *(_DWORD *)(a1 + 268) = 1056964608;
```
1056964608 is the IEEE 754 for 0.5 single precision (4 bytes), yet the next element starts in 8 bytes.
the same value doesn't make sense for double precision.

so either the next property 268 has to be padded by 4 bytes or 260 is a large integer property property (`long` ) where the default value can fit an `int`.

for now i will probably pad the values.

**Comment by naomichan** [comment]
it's probably two floats, it's writing it as a memory buffer and then reading that buffer directly with pointers and casting it.

So it's only reading 4 bytes and casting it to a float.

in other words, two floats, one is just zero and this is a compiler optimization.

**Comment by lobolmart** [comment]
do i need to pad the second float (268) by 4 bytes in the generated .CS output, in the lines of?
```
[NMS(Size = 4, Ignore = true)]
public byte[] PaddingXX;
```

**Comment by naomichan** [comment]
the value at offset 260 is a float (QWORD UPPER)
264 is another float (QWORD LOWER)
268 is yet another float (DWORD)

**Comment by lobolmart** [comment]
ok i see, will add a check for that.

**Comment by emoose** [comment]
Also @naomichan, unfortunately not all of the mbins have the timestamp set :( seems that at some point they stopped putting timestamps in the files, so the only ones with timestamps set are usually older ones with different structures.

Maybe the unknown 8 bytes before the template name can be used for version tracking though, if they aren't linked to the file name and they change each time the MBIN is built, we could possibly make lists of these 8 byte identifiers for each update of the game and then assign an UpdateVersion to the MBINFile class based on what list the files identifier is found in. A bit of work, but the only real way I can see for us to track versions.

Or possibly it's only the files built for release that don't have the timestamp set, maybe it's added for updated files, I've only really looked at the 1.03 files so far.

**Comment by lobolmart** [comment]
update:
- auto byte[] padding
- show suggestions if an offset is accessed with a smaller size pointer [1]
- catch packed two floats into a QWORD as @naomichan suggested
- subroutine placeholders [2]

in:
https://gist.github.com/lobolmart/d959a96166b033d153f42faae19b103c
out:
https://gist.github.com/lobolmart/5bb618857a587fbc5c799d9bf5d40fa9

[1] e.g.:
```
		public bool Unknown3CA4;		 // offset: 15524, sz: 1, origin: 1, parsed: 1

		// missing 3 bytes at offset 15524
		// does 15524 contain a DWORD?
		[NMS(Size = 0x3, Ignore = true)]
		public byte[] Padding3CA5;		// offset: 15525, sz: 3, comment: auto padding 
```

[2] the only sub called in the gcuiglobals sub is sub_140162E50, which has a do-while loop and i don't think it's a child template(?).
(there is also a do-while loop in the gcuiglobals sub as well)
currently there is no support for do-while loops and those bytes are padded. do-while expansion might be a thing.

other than that sub expansion is doable in the lines of such input:
```
global_template_sub_of_interest()
{
    // some_child_sub() is used here
}
// i.e. the child subs are copy pasted as blocks bellow the sub of interests
some_child_sub()
{
}
```

**Comment by lobolmart** [comment]
[messy codes](https://github.com/lobolmart/MBINRawTemplateParser)

**Comment by lobolmart** [comment]
hi @emoose,

is it OK to

**Comment by emoose** [comment]
@lobolmart yeah that'd be fine, but they should probably be taken out once we've made sure the structure & types are correct

**Comment by lobolmart** [comment]
https://github.com/emoose/MBINCompiler/pull/87
