### ISSUE TITLE
Biomes seems to be broken after compile

### ISSUE THREAD

**Issue by SystemOFF** [emoose/MBINCompiler#76]
Hello there!
RADIOACTIVEOBJECTSFULL.MBIN / LOW / MID files not working after compiling it back to mbin

Just compile exml that not changed back to mbin file and look for changes in the game. (All objects are disappeared in the game)

Thanks for this amazing tool!
Victor.

**Comment by Bananasft** [comment]
Related to #69?

**Comment by SystemOFF** [comment]
Yes, thank you

**Comment by emoose** [comment]
I spent a good hour trying to get the MBIN to match with the original, and it was all down to a missing padding field in one of the structures. Oh well, at least we have MBINC compiling working a bit better now. (meanwhile the death cry of #67 can still be heard in the distance...)

Can you test recompiling that MBIN again using a newly decompiled EXML, and see if that works ingame? There's still some differences in the structure, but they're minor and hopefully won't affect much.

**Comment by SystemOFF** [comment]
It works! At least the objects do not disappear, thanks!
