### ISSUE TITLE
Missing data decompiling GSSolargenerationglobals.globals.mbin

### ISSUE THREAD

**Issue by Lo2k** [emoose/MBINCompiler#81]
Hi again :)

I just tried to make some tests in the file given in title and got no result.
So I decompiled/recompiled original file and recompiled one is missing the 60 last bytes.
I also checked the .exml and it also misses the values stored in the 60 last bytes of the original file, so it seems something doesn't work when decompiling this file.

Could you have a look at it ?

Regards

**Comment by Lo2k** [comment]
As it seems I can edit my first post for now, I just wanted to specify this file is directly into GAMEDATA\PCBANKS

**Comment by emoose** [comment]
Thanks for the report, should be fixed in the latest commit (forgot to define something as an array :100:)

**Comment by Lo2k** [comment]
It works perfectly. Thanks for your quick fix
