### ISSUE TITLE
MBINCompiler.csproj and line endings

### ISSUE THREAD

**Issue by lobolmart** [emoose/MBINCompiler#83]
anytime i add files to the project in VS2015, MBINCompiler.csproj is updated with DOS LEs while the one in the repo (original) is with UNIX LEs, which causes a big diff for said file. :(

is there a way to make VS2015 to use UNIX LEs for MBINCompiler.csproj?

**Comment by emoose** [comment]
There's a way for git to convert DOS to Unix auto, https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings should help.

Not sure if that takes effect on diffing though, but I've got it enabled and the diffs have always been fine for me so I guess it does.

**Comment by lobolmart** [comment]
thanks, i was looking for a VS2015 option, but i guess core.autocrlf would do for now.

**Comment by Guard13007** [comment]
For future reference, you should probably always be doing this in your global gitconfig. The same problem crops up everywhere and this fixes it without you having to worry.

**Comment by lobolmart** [comment]
i've contributed to projects which are very strict about line endings and whitespace, so autocrlf was never an option.

from my POV, i see it mostly as a VS2015 issue, since they are yet to sort the software messing up the line endings.
